persistent_worker:
  isolation:
    container:
      image: debian:latest
      cpu: 1
      memory: 2G
      volumes:
         - /:/ha-this-is-the-hosts-full-filesystem/
      #   - /tmp/persistent-cache:/tmp/cache:ro

task:
  script: uname -a
